server:
  port: 8022

ci2:
  srvhost: DESKTOP-UP64I3U

eureka:
  instance:
    hostname: ${ci2.srvhost}
    lease-expiration-duration-in-seconds: 60
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    renewal-threshold-update-interval-ms: 10000
    enable-self-preservation: false
