server:
  port: 7057

spring:
  application:
    name: demo-server
  cloud:
    client:
      hostname: localhost

worker:
  name: David

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8022/eureka/